### ISSUE TITLE
Expected unit of acceleration in counts function?

### ISSUE THREAD

**Issue by vincentvanhees** [walkabillylab/activityCounts#1]
What is the expected unit of measurement for the data argument in function counts()?

When I express the data in _mg_ units the mean count is around 500, while when expressed in _g_ it is around 3, so I am guessing the expected unit of measurement is _mg_. Can you please confirm?

**Comment by walkabilly** [comment]
The unit for counts is unclear. The unit is not _g_ or m/s2. This method replicates Actigraph counts, which are proprietary. You can read about counts from Actigraph here (https://s3.amazonaws.com/actigraphcorp.com/wp-content/uploads/2017/11/26205758/ActiGraph-White-Paper_What-is-a-Count_.pdf) and here (https://actigraphcorp.force.com/support/s/article/What-are-counts).

**Comment by vincentvanhees** [comment]
Thanks for your quick reply. I was not referring to the output of the function, but to the input argument 'data' in the counts() function. The function documentation currently does not clarify the unit of the raw acceleration values that go into the function.

PS. I am aware of lack of transparency of counts. I was the one who inspired Jan Brond to develop his algorithm with [this](https://ieeexplore.ieee.org/abstract/document/5534986/footnotes) paper. It was clear that imitating counts was not straightforward, so I lost interest to continue the development.

**Comment by vincentvanhees** [comment]
In other words but now with specific reference to the code:

The [counts function documentation](https://github.com/walkabillylab/activityCounts/blob/master/R/counts.R) states:

`#' @param data Accelerometer data, Must have at least three columns.`

What should be the unit of the values that go into this data object?
Thanks for your time to look into this.

**Comment by khataei** [comment]
Thank you @vincentvanhees for the question. The short answer is that the unit is g.

The long answer is that the package is developed and tested based on the acceleration data produced by Actigraph GT3X+. According to the[ user manual of Actigraph GT3X+](http://s3.amazonaws.com/actigraphcorp.com/wp-content/uploads/2018/02/22094126/GT3X-wGT3X-Device-Manual-110315.pdf), acceleration is measured in the units of gravity (G's). It seems that here, G refers to acceleration relative to free-fall acceleration, not the universal gravitational constant (which is 6.674×10−11 m3⋅kg−1⋅s−2). To be more precise here, we can state that the reported acceleration by Actigraph is unitless. I think Actigraph is calibrated against standard gravity(9.80665 m/s2 or 32.17405 ft/s2), so when it reports the acceleration, it is technically dividing the acceleration by standard gravity, and that makes the reported acceleration unitless. 

So to use the package, if our acceleration is reported in the SI units(m/s2), we need to divide it by 9.80665. If our sensor measures acceleration in the Imperial system(ft/s2), we need to divide it by 32.17405 ft/s2. If our sensor returns acceleration relative to gravity, similar to what Actigraph does, we don't need any modification. I hope this helped.

**Comment by vincentvanhees** [comment]
Thanks for clarifying!
