### ISSUE TITLE
Missing versioning and change log

### ISSUE THREAD

**Issue by vincentvanhees** [walkabillylab/activityCounts#8]
As discussed over e-mail, I have now removed activityCounts as a dependency of the GGIR package as there are a number of issues that worry me. If you need help addressing these then let me know.

- GitHub master branch is not consistent with counts derived from current CRAN version 0.1.2. The repo does not have a change log to describe what has changed and it is unclear whether the one unit-test covers all essential functionality. As a result, I find it hard to oversee whether the package still functions in line with the work by Jan Brond.
- I see activityCounts has undergone changes in recent years on GitHub but no effort has been made to create a GitHub release or to  keep CRAN version up to date. It would be helpful if you could adopt the habit of making numbered GitHub and CRAN releases once in a while as long as the code is under development.
- ggplot2 is used as a dependency only for the purpose of creating a simple scatter plot in the vignette. This seems overkill and a simple base::plot() would be sufficient and make the package lighter.

**Comment by walkabilly** [comment]
> GitHub master branch is not consistent with counts derived from current CRAN version 0.1.2. The repo does not have a change log to describe what has changed and it is unclear whether the one unit-test covers all essential functionality. As a result, I find it hard to oversee whether the package still functions in line with the work by Jan Brond.

The package still functions in line with Brond. I will add a few more test examples to the data to ensure that users can test the functionality of the package. 

> I see activityCounts has undergone changes in recent years on GitHub but no effort has been made to create a GitHub release or to keep CRAN version up to date. It would be helpful if you could adopt the habit of making numbered GitHub and CRAN releases once in a while as long as the code is under development.

I have included a CHANGELOG.md file, which replaced the NEWS.md file. I have specified the changes in version 0.1.3 and will update the CRAN release soon. 

> ggplot2 is used as a dependency only for the purpose of creating a simple scatter plot in the vignette. This seems overkill and a simple base::plot() would be sufficient and make the package lighter.

Will update this in the CRAN release.

**Comment by vincentvanhees** [comment]
Thanks Daniel.

It would be good if you could not only add a version number in the changelog but also create a GitHub release (right side of the screen in GitHub), because that will create a tag in the git history and make it easier to install specific versions of the package.

I had a test in the GGIR package code that evaluated whether the activityCounts output is consistent. This test passes with activityCounts 0.1.2 on CRAN but not with the latest GitHub version. This gives the impression that something has changed. Maybe you fixed a bug and the new values are better or maybe a bug was introduced by which the old version is better.

To reproduce, see code below. You will need to remove activityCounts and restart RStudio in between the tests to ensure different version of the package are used:

```
library(testthat)
library(remotes)

# Comment out one of the following two lines to choose which version to use:
# activityCounts_version = "CRAN_0.1.2"
activityCounts_version = "GitHub_latest"

if (activityCounts_version == "CRAN_0.1.2") {
  install_github("walkabillylab/activityCounts", ref = '91fbfc681ce83ac7f8717d5d4a24b1a29539a222', force = TRUE) # commit from 26 July 2019 right before the 0.1.2 release on CRAN
  
} else {
  install_github("walkabillylab/activityCounts", force = TRUE) # latest version
}

install_github("wadpac/GGIR", ref = '2.8-0') # last GGIR version that had activityCounts as a dependency

library(activityCounts)
library(GGIR)

# Create test file
Ndays = 2
GGIR:::create_test_acc_csv(Nmin = Ndays * 1440, sf = 30) # this creates a synthetic ActiGraph csv file
fn = "123A_testaccfile.csv"
metadatadir = paste0(getwd(), "/output_test")
dn = "output_test"
if (file.exists(dn))  unlink(dn, recursive = TRUE)
# Run GGIR with activityCounts as dependency
GGIR::g.part1(datadir = fn, outputdir = getwd(), f0 = 1, f1 = 1, overwrite = TRUE, desiredtz = "Europe/London",
              studyname = "test", do.cal = FALSE, 
              do.enmo = TRUE,do.brondcounts = TRUE,
              windowsizes = c(15,3600,3600), do.parallel = FALSE,
              minimumFileSizeMB = 0)
rn = dir("output_test/meta/basic/",full.names = TRUE)
load(rn[1])

# Check output
expect_equal(sum(M$metashort$BrondCount_x), 17690)
expect_equal(sum(M$metashort$BrondCount_y), 60971)
expect_equal(sum(M$metashort$BrondCount_z), 957584)
```

when I run this on CRAN version (0.1.2) the tests pass, when I run it on the latest GitHub version I get:

![image](https://user-images.githubusercontent.com/8362333/195805610-46150f8a-1926-4f28-bde1-9d3a24b36386.png)

<details>
  <summary>sessionInfo()</summary>
  
 ```
> sessionInfo()
R version 4.2.1 (2022-06-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.1 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.10.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.10.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=C                  LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=nl_NL.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=nl_NL.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=nl_NL.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] GGIR_2.8-0           activityCounts_0.1.3 remotes_2.4.2        testthat_3.1.4      

loaded via a namespace (and not attached):
 [1] pkgload_1.3.0      sass_0.4.2         shinyFiles_0.9.2   jsonlite_1.8.2     bslib_0.4.0        brio_1.1.3        
 [7] shiny_1.7.2        assertthat_0.2.1   tuneR_1.4.0        lattice_0.20-45    pillar_1.8.1       glue_1.6.2        
[13] digest_0.6.29      promises_1.2.0.1   htmltools_0.5.3    httpuv_1.6.6       seewave_2.2.0      pkgconfig_2.0.3   
[19] xtable_1.8-4       processx_3.7.0     later_1.3.0        tibble_3.1.8       proxy_0.4-27       generics_0.1.3    
[25] ellipsis_0.3.2     DT_0.24            cachem_1.0.6       withr_2.5.0        shinyjs_2.1.0      cli_3.4.1         
[31] magrittr_2.0.3     crayon_1.5.2       mime_0.12          ps_1.7.1           fs_1.5.2           fansi_1.0.3       
[37] MASS_7.3-58        class_7.3-20       pkgbuild_1.3.1     tools_4.2.1        data.table_1.14.2  prettyunits_1.1.1 
[43] lifecycle_1.0.3    stringr_1.4.1      callr_3.7.1        signal_0.7-7       compiler_4.2.1     jquerylib_0.1.4   
[49] e1071_1.7-11       rlang_1.0.6        classInt_0.4-8     units_0.8-0        grid_4.2.1         rstudioapi_0.14   
[55] htmlwidgets_1.5.4  DBI_1.1.3          curl_4.3.2         R6_2.5.1           zoo_1.8-11         lubridate_1.8.0   
[61] dplyr_1.0.10       fastmap_1.1.0      utf8_1.2.2         rprojroot_2.0.3    desc_1.4.1         KernSmooth_2.23-20
[67] stringi_1.7.8      Rcpp_1.0.9         vctrs_0.4.2        sf_1.0-8           tidyselect_1.2.0  
```


</details>

**Comment by vincentvanhees** [comment]
I am now scrolling through the changes since 0.1.2: https://github.com/walkabillylab/activityCounts/compare/91fbfc6...master and it seems this [commit](https://github.com/walkabillylab/activityCounts/commit/463adb168b7dab2a095e6a2b0171e33c6e13256f ) in counts.R is what caused the differences I found above. Previously `B = B * gain` was applied for every value of `i`, while now it is only applied once. This should then explain why the 2nd and 3rd axes of counts are different as I found above. 

So, it sounds like this was a correct fix to a real bug. It would be good to have in the changelog for the new version the following line: "Bug fixed in gain multiplication inside function counts, breaking consistency with previous versions of the code."

**Comment by walkabilly** [comment]
I've made the suggested changes and created a Github release for version 0.2.0. There are a number of changes but I think the most important is that I'm now the maintainer. SeyedJavad has moved on and this was work from his MSc in Computer Science. I will send the package to CRAN for review on Monday.
